dependencies:
  build:
    - node:12.16.3

build_targets:
  - name: default
    commands:
      - npm install
      - npm test
    environment:
      - NODE_ENV=development
    host_only: true
  - name: test
    commands:
      - npm test
    environment:
      - NODE_ENV=development
    host_only: true

exec:
  commands:
    - npm start
  environment:
    default:
      - NODE_ENV=development
  host_only: true

ci:
  builds:
    - name: default
      build_target: default
